-- MySQL Script generated by MySQL Workbench
-- Mon Jan 13 23:16:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ieduca_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ieduca_test` ;

-- -----------------------------------------------------
-- Schema ieduca_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ieduca_test` DEFAULT CHARACTER SET utf8 ;
USE `ieduca_test` ;

-- -----------------------------------------------------
-- Table `ieduca_test`.`datos_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieduca_test`.`datos_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(30) NULL,
  `correo` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ieduca_test`.`datos_familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieduca_test`.`datos_familia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `tipo_familiar` VARCHAR(1) NOT NULL,
  `datos_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `datos_persona_id`),
  INDEX `fk_datos_familia_datos_persona_idx` (`datos_persona_id` ASC),
  CONSTRAINT `fk_datos_familia_datos_persona`
    FOREIGN KEY (`datos_persona_id`)
    REFERENCES `ieduca_test`.`datos_persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ieduca_test`.`datos_persona_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ieduca_test`.`datos_persona_2` (
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(30) NULL,
  `correo` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
